# Generated by Django 6.0.2 on 2026-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('canteen', 'Canteen Staff'), ('ngo', 'NGO')], default='student', max_length=20),
        ),
    ]
