# Generated by Django 6.0.2 on 2026-03-27 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_canteen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='canteen',
            field=models.ForeignKey(blank=True, help_text='Canteen this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.canteen'),
        ),
    ]
