# Generated by Django 6.0.2 on 2026-03-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_canteen_userprofile_canteen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='canteen',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('canteen', 'Canteen'), ('hostel', 'Hostel'), ('mess', 'Mess'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('temple', 'Temple'), ('ngo', 'NGO')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('canteen', 'Canteen'), ('hostel', 'Hostel'), ('mess', 'Mess'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('temple', 'Temple')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_provider',
            field=models.ForeignKey(blank=True, help_text='Food Provider this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.foodprovider'),
        ),
    ]
