# Generated by Django 6.0.2 on 2026-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fooditem_food_provider'),
        ('meals', '0004_mealbooking_food_provider'),
        ('surplus', '0004_surplusfood_food_provider'),
        ('users', '0004_remove_canteen_managed_by_remove_userprofile_canteen_and_more'),
        ('waste', '0003_remove_wastelog_canteen_wastelog_food_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canteen',
        ),
    ]
