# Generated by Django 6.0.2 on 2026-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending Selection'), ('student', 'Student'), ('admin', 'Admin'), ('canteen', 'Canteen'), ('hostel', 'Hostel'), ('mess', 'Mess'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('temple', 'Temple'), ('ngo', 'NGO')], default='pending', max_length=20),
        ),
    ]
