# Generated by Django 6.0.2 on 2026-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealbooking_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealbooking',
            name='canteen',
        ),
    ]
