# Generated by Django 6.0.2 on 2026-03-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_canteen_managed_by_remove_userprofile_canteen_and_more'),
        ('waste', '0002_wastelog_canteen_alter_wastelog_logged_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastelog',
            name='canteen',
        ),
        migrations.AddField(
            model_name='wastelog',
            name='food_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='users.foodprovider'),
        ),
    ]
