# Generated by Django 6.0.2 on 2026-03-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_fooditem_canteen'),
        ('users', '0004_remove_canteen_managed_by_remove_userprofile_canteen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='users.foodprovider'),
        ),
    ]
