# Generated by Django 5.2.12 on 2026-03-27 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('collected', 'Collected')], default='available', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_added', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
