# Generated by Django 6.0.2 on 2026-03-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0001_initial'),
        ('users', '0003_canteen_userprofile_canteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfood',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_items', to='users.canteen'),
        ),
    ]
