# Generated by Django 6.0.2 on 2026-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0002_surplusfood_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplusfood',
            name='canteen',
        ),
    ]
